spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/server
    username: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

#  spring.datasource.url=jdbc:h2:mem:testdb
#  spring.datasource.driverClassName=org.h2.Driver
#  spring.datasource.username=root
#  spring.datasource.password=password
#  spring.h2.console.enabled=true
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect